# Длины полей
NAME_MAX_LENGTH = 124
SURNAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 15
ABOUT_MAX_LENGTH = 256

# Настройки аватара
AVATAR_SIZE = 200
AVATAR_FONT_FACTOR = 0.6
AVATAR_TEXT_COLOR = "white"
AVATAR_BG_MIN = 50
AVATAR_BG_MAX = 200
